//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POO1_Tarea06_TrujilloMezaJhuli.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Negocios2022Entities : DbContext
    {
        public Negocios2022Entities()
            : base("name=Negocios2022Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_categorias> tb_categorias { get; set; }
        public virtual DbSet<tb_clientes> tb_clientes { get; set; }
        public virtual DbSet<tb_empleados> tb_empleados { get; set; }
        public virtual DbSet<tb_paises> tb_paises { get; set; }
        public virtual DbSet<tb_pedidoscabe> tb_pedidoscabe { get; set; }
        public virtual DbSet<tb_productos> tb_productos { get; set; }
        public virtual DbSet<tb_proveedores> tb_proveedores { get; set; }
        public virtual DbSet<tb_pedidosdeta> tb_pedidosdeta { get; set; }
    
        public virtual ObjectResult<usp_ProductoListar_Result> usp_ProductoListar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ProductoListar_Result>("usp_ProductoListar");
        }
    }
}
