//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POO1_Tarea07_TrujilloMezaJhuli.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_clientes()
        {
            this.tb_pedidoscabe = new HashSet<tb_pedidoscabe>();
        }
    
        public string IdCliente { get; set; }
        public string NombreCia { get; set; }
        public string Direccion { get; set; }
        public string idpais { get; set; }
        public string Telefono { get; set; }
    
        public virtual tb_paises tb_paises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pedidoscabe> tb_pedidoscabe { get; set; }
    }
}
